/*
 * TIMER0_configuration.h
 *
 *  Created on: Sep 17, 2023
 *      Author: ahmed
 */

#ifndef TIMER_0_TIMER0_CONFIGURATION_H_
#define TIMER_0_TIMER0_CONFIGURATION_H_

/* CHOOSE PRESCALER:
 *
 *  TIMER0_PRESCALER_1
 *  TIMER0_PRESCALER_8
 *  TIMER0_PRESCALER_64
 *  TIMER0_PRESCALER_256
 *  TIMER0_PRESCALER_1024
 *  TIMER0_PRESCALER_EXTCLK_FALLING_EDGE
 *  TIMER0_PRESCALER_EXTCLK_RISING_EDGE
 */


/* CHOOSE TIMER0 MODE:
 *
 * TIMER0_NORMAL_MODE
 * TIMER0_CTC_MODE
 * TIMER0_FAST_PWM
 * TIMER0_PHASE_CORRECT_PWM
 */


/* CHOOSE OC0 MODE:
 *
 * FOR NON PWM MODE (NORMAL & CTC):
 *    OC0_DISCONNECTED
 *    TOGGLE_OC0_ON_COMPARE_MATCH
 *    CLEAR_OC0_ON_COMPARE_MATCH
 *    SET_OC0_ON_COMPARE_MATCH
 *
 * FOR PWM MODE (FAST & PHASE CORRECT)
 *    OC0_DISCONNECTED
 *    OC0_INVERTING_MODE
 *    OC0_NON_INVERTING_MODE
 */
#define  CPU_F              8
#define  TIMER0_PRESCALER   TIMER0_PRESCALER_8
#define  TIMER0_MODE        TIMER0_FAST_PWM
#define  TIMER0_OC0_MODE    OC0_NON_INVERTING_MODE

#endif /* TIMER_0_TIMER0_CONFIGURATION_H_ */
